### ISSUE TITLE
Error when import UniGame Builds Command Package

### ISSUE THREAD

**Issue by takaaptech** [UniGameTeam/UniBuild.Commands#1]
Hi @Mefodei 
Please check this image bellow

![image](https://user-images.githubusercontent.com/6276251/114810892-35bc6280-9dd7-11eb-8e82-0b586283da0d.png)

**Comment by Mefodei** [comment]
Hi @takaaptech
Check that issue today

**Comment by Mefodei** [comment]
![image](https://user-images.githubusercontent.com/7457166/114937157-1872ad00-9e46-11eb-87e9-ee018cabb8a1.png)

u can update now @takaaptech
